### ISSUE TITLE
Annotation dialog missing

### ISSUE THREAD

**Issue by lebogan** [whacked/calibre-viewer-annotation#3]
Hi Whacked,
I really want this to work! I installed as per the instructions and nothing. My environment:

Fedora 23 workstation
Calibre 2.49
Python 2.7.10
Sqlalchemy 1.0.12 Location: /usr/lib64/python2.7/site-packages

I edited ViewerAnnotationPlugin/annotator_model.py for the hacked path and ran
```
calibre-customize .
```
That is a 'dot' at the end. Right? There was no out from that command, and no errors. Do I need to explicitly enable this plugin?

I greatly appreciate any insight you can offer. This is my default epub viewer.

Lewis

**Comment by lebogan** [comment]
Please, disregard. I need new glasses.

**Comment by whacked** [comment]
I assume you got it working, but the documentation probably needs to be clearer. What was the main issue here? Did everything work like you expected?

**Comment by lebogan** [comment]
My fault. I missed the '-b' switch on 'calibre-customize' command. That
fixed the install and it is working though, not without some issues.
When I annotate, certain characters - 'l', 'o', 'backspace', etc -
either don't print or cause command-lick actions. Weird. Not sure how
to track that down. The documentation seems to be clear enough. Are you
interested in the anomalies I see here?

**Comment by whacked** [comment]
I can't reproduce the key issues on my system, though it resembles a hotkey binding problem. Do you know if those keys launch any particular behavior, or if you have any plugins that utilize those keys?
